### ISSUE TITLE
Secret key backup not working

### ISSUE THREAD

**Issue by veisis** [passbolt/passbolt_firefox#2]
Secret key backup saving is broken. File passbolt_private.asc contains string "null".
Or maybe secret key generation is not working in add-on. Using Firefox 49.01 and passbolt add-on version 1.1.1

**Comment by stripthis** [comment]
Hi @veisis, this is to confirm that we could reproduce the issue. We will provide a fix as soon as possible. We've also identified an issue with our automated tests that prevented us to test this.

ref. PASSBOLT-1698

**Comment by stripthis** [comment]
@veisis this issue was fixed in release v.1.2.0. Feel free to reopen if the problem persists. Thanks,
